### ISSUE TITLE
PythonSDK Keep crashing when I open my game from Epic

### ISSUE THREAD

**Issue by IceCrusher07** [bl-sdk/bl2-mod-manager#5]
2024-March-02, I just download the python .zip, and I cant seem to make it work with my game on epic Version: 2.0.2_BN160_CL2863302

**Comment by apple1417** [comment]
If it crashes on launch most likely you have an outdated/bad plugin in your plugins folders, delete it. The sdk itself won't cause this. Join the [support discord](https://discord.gg/bXeqV8Ef9R) for better real-time help/debugging.
